contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #nfphasing channel"
    url: https://nfcore.slack.com/channels/nfphasing
    about: Discussion about the nf-core/nfphasing pipeline
